### ISSUE TITLE
Use action instead of ROM for install

### ISSUE THREAD

**Issue by Toylerrr** [azuravian/playnite-LocalInstallButton#2]
Any way to have the install button tie to an action instead of the ROM portion?

This way we could use variables in the location so we can bulk edit adding actions. Currently using ROMs we cant use variables or exe arguments.

![image](https://user-images.githubusercontent.com/4400902/161447412-54cdbac4-71fc-42aa-9736-25c6d6fc8abd.png)

**Comment by azuravian** [comment]
I'll look into adding an option for this.  It would probably be an either/or setup (i.e. you could check a box in settings to use this instead of the ROMS section).

Just to be clear on what you want.  When I read the Install action, it should run whatever executable is in the Path field, using the arguments specified in Arguments?  Will you be installing anything from an ISO or always directly from an exe?

**Comment by Toylerrr** [comment]
> Just to be clear on what you want.  When I read the Install action, it should run whatever executable is in the Path field, using the arguments specified in Arguments?  Will you be installing anything from an ISO or always directly from an exe?

Always an exe, I'm packaging my games with WinRAR SFX to an exe and use playnite to pass variables to determine the install location so it's pretty much automated so it would be "a:/games/getting over it.exe" -d "g:/games/getting over it"
